std_msgs/Header header

uint8 motor1_online
uint16 motor1_ecd
int16 motor1_rpm
int16 motor1_current
uint8 motor1_temperature

uint8 motor2_online
uint16 motor2_ecd
int16 motor2_rpm
int16 motor2_current
uint8 motor2_temperature

uint8 motor3_online
uint16 motor3_ecd
int16 motor3_rpm
int16 motor3_current
uint8 motor3_temperature

uint8 motor4_online
uint16 motor4_ecd
int16 motor4_rpm
int16 motor4_current
uint8 motor4_temperature
