slaves:
  - sn2228293:
      sdo_len: !uint16_t 7
      task_count: !uint8_t 3
      latency_pub_topic: !std::string '/ecat/sn2228293/latency'

      tasks:
        - app_1:
            sdowrite_task_type: !uint8_t 1
            pub_topic: !std::string '/ecat/sn2228293/app1/read'
            pdoread_offset: !uint16_t 0
        - app_2:
            sdowrite_task_type: !uint8_t 3
            pub_topic: !std::string '/ecat/sn2228293/app2/read'
            pdoread_offset: !uint16_t 19
        - app_3:
            sdowrite_task_type: !uint8_t 4
            sdowrite_dshot_id: !uint8_t 1
            sdowrite_init_value: !uint16_t 0
            sub_topic: !std::string '/ecat/sn2228293/app3/write'
            pdowrite_offset: !uint16_t 0
